[client]
toolbarMode = "viewer"
showErrorDetails = false
sidebarState = "expanded"
showSidebarNavigation = false
themeBase = "dark"
showMenuItems = false

[logger]
level = "critical"

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[server]
headless = true
enableXsrfProtection = true
maxUploadSize = 50
runOnSave = false
useServerTime = true

[ui]
hideTopBar = true
hideFooter = true

[theme]
base = "dark"
primaryColor = "#ef4444"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#111827"
textColor = "#e5e7eb"
font = "sans serif"